---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cyberchef.fullname" . }}-config
  labels:
    {{- include "cyberchef.labels" . | nindent 4 }}
  {{- with include "cyberchef.annotations" (dict "root" .) }}
  {{- trim . | nindent 2 }}
  {{- end }}
data:
  {{- include "cyberchef.configData" . | nindent 2 }}
