apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cyberchef.fullname" . }}
  labels:
    {{- include "cyberchef.labels" . | nindent 4 }}
  {{- with include "cyberchef.annotations" (dict "root" . "annotations" .Values.deploymentAnnotations) }}
  {{- trim . | nindent 2 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cyberchef.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include "cyberchef.configData" . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "cyberchef.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      enableServiceLinks: {{ .Values.enableServiceLinks }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cyberchef.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ include "cyberchef.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if or .Values.env .Values.extraEnv }}
          env:
            {{- with .Values.env }}
            {{- range $name, $value := . }}
            - name: {{ $name }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /tmp
              name: tmp
            - mountPath: /etc/nginx/conf.d/default.conf
              name: cyberchef-config
              readOnly: true
              subPath: default.conf
            - mountPath: /etc/nginx/nginx.conf
              name: cyberchef-config
              readOnly: true
              subPath: nginx.conf
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: tmp
          {{- if .Values.tmpVolume.sizeLimit }}
          emptyDir:
            sizeLimit: {{ .Values.tmpVolume.sizeLimit | quote }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: cyberchef-config
          configMap:
            name: {{ include "cyberchef.fullname" . }}-config
            items:
              - key: default.conf
                path: default.conf
              - key: nginx.conf
                path: nginx.conf
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- else if .Values.defaultPodAntiAffinity.enabled }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    {{- include "cyberchef.selectorLabels" . | nindent 20 }}
                topologyKey: {{ .Values.defaultPodAntiAffinity.topologyKey | quote }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
