{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "cyberchef.fullname" . }}
  labels:
    {{- include "cyberchef.labels" . | nindent 4 }}
  {{- with include "cyberchef.annotations" (dict "root" .) }}
  {{- trim . | nindent 2 }}
  {{- end }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "cyberchef.selectorLabels" . | nindent 6 }}
{{- end }}
